//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagement.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Container
    {
        public int ContainerID { get; set; }
        public string ContainerName { get; set; }
        public Nullable<int> VesselID { get; set; }

        public virtual Vessel Vessel { get; set; }

    
    }
}
