//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.EnterpriseServices;

    public partial class Vessel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vessel()
        {
            this.Containers = new HashSet<Container>();
        }
    
        public int VesselID { get; set; }
        public string VesselName { get; set; }
        public int MaxLoad { get; set; }
        public Nullable<int> FleetID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Containers { get; set; }
        public virtual Fleet Fleet { get; set; }

        public bool checkLoad(){

            int load = 0;

            foreach (Container container in Containers)
            {
                load += 1;
            }

            if (load >= MaxLoad)
                return false;

            return true;
        }
    }
}
